src/objects/Candidate_Badge__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Candidate Badges</relationshipLabel>
        <relationshipName>Candidate_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Candidate Badge</label>
    <nameField>
        <displayFormat>CB-{000000}</displayFormat>
        <label>User Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BadgeUtils_Test.cls
@IsTest
private class BadgeUtils_Test 
{
    @IsTest
    static void AssignBadgeIfPathComplete_Test()
    {
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c path=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);

        Candidate_Path__c cp=DataAccessor.GetOrCreateCandidatePath(path.id, UserInfo.GetUserId());
        List<Candidate_Step__c> cSteps=[select id, Complete__c 
                                        from Candidate_Step__c
                                        where Candidate_Path__c=:cp.id];

        for (Candidate_Step__c cStep : cSteps)
        {
            cStep.Complete__c=true;
        }
        update cSteps;

        BadgeUtils.AssignBadgeIfPathComplete(new List<Candidate_Path__c>{cp});

        List<Candidate_Badge__c> cBadges=[select id from Candidate_Badge__c];
        System.assertEquals(1, cBadges.size());
    }
}