src/objects/Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>Badge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Training Paths</relationshipLabel>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Training_Step__c.object
<CustomObject>
    <fields>
        <fullName>Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>Training_Path__c</referenceTo>
        <relationshipLabel>Training Steps</relationshipLabel>
        <relationshipName>Training_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Step</label>
    <nameField>
        <label>Training Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrainingHome_Test.cls
@IsTest
private class TrainingHome_Test 
{
    static void SetService()
    {           
        TrainingServiceIF service=new TrainingServiceLocalImpl();
        TrainingHome.SetTrainingService(service);
    }

    @IsTest
    static void GetPaths_Test()
    {
        SetService();
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c path=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);
        List<TrainingPath> paths=TrainingHome.GetPaths(null);

        System.assertEquals(1, paths.size());
    }

    @IsTest
    static void GetPath_Test()
    {
        SetService();
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c tPath=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);
        TrainingPath path=TrainingHome.GetPath(null, tPath.id);

        System.assertEquals('Unit Test', path.name);
    }

    @IsTest
    static void GetStep_Test()
    {
        SetService();
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c tPath=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);
        Candidate_Path__c cp=DataAccessor.GetOrCreateCandidatePath(tPath.id, UserInfo.GetUserId());
        Training_Step__c tStep=[select id from Training_Step__c
                                where Training_Path__c=:tPath.id][0];
        TrainingPath path=TrainingHome.GetStep('', tPath.Id, tStep.Id);
        System.assertEquals(tStep.Id, path.steps[0].id);
    }

    @IsTest
    static void PassStep_Test()
    {
        SetService();
        Badge__c badge=TrainingTestFixtures.GetBadge('Test');
        Training_Path__c tPath=TrainingTestFixtures.GetTrainingPath('Unit Test', badge.id);
        Candidate_Path__c cp=DataAccessor.GetOrCreateCandidatePath(tPath.id, UserInfo.GetUserId());
        Training_Step__c tStep=[select id from Training_Step__c
                                where Training_Path__c=:tPath.id][0];
        Boolean pathComplete=TrainingHome.PassStep('', tPath.Id, tStep.Id);
        System.assertEquals(true, pathComplete);
    }

    @IsTest 
    static void GetUserInfo()
    {
        SetService();
        TrainingHome.GetUserInfo('');
    }

    @IsTest 
    static void GetAllEndpoints_Test()
    {
        SetService();
        List<TrainingEndpoint> eps=TrainingHome.GetAllEndpoints();
        System.assertEquals(1, eps.size());
    }
}